version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: clinic-db
    restart: always
    environment:
      POSTGRES_DB: clinic
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - clinic-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d clinic"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

#  clinic-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: clinic-app
#    depends_on:
#      postgres:
#        condition: service_healthy
#    environment:
#      - DB_HOST=postgres
#      - DB_PORT=5432
#      - POSTGRES_DB=clinic
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=admin
#    ports:
#      - "8080:8080"
#    restart: on-failure

volumes:
  clinic-db-data:
