spring:
  application:
    name:
      clinic-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:clinic}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

old-system:
  host: ${OLD_SYSTEM_HOST:http://localhost:8081}

import:
  notes:
    cron: "0 15 */2 * * *"
    batch-size: 100
    date-range-days: 30

logging:
  level:
    org.example.clinicservice: DEBUG
    feign: DEBUG
